// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvgxsiptmymvwgsnseae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Z3hzaXB0bXltdndnc25zZWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODUxNjIsImV4cCI6MjA3NDQ2MTE2Mn0.2ySiE5snSXU_BxReb1jvHaVg2JKjwWxEkXcIl-rHzm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});